### ISSUE TITLE
Plugin stopped working in ST 3103

### ISSUE THREAD

**Issue by certainlyakey** [randy3k/ChangeList#11]
In the latest version it seems that the plugin stopped working completely. The commands execute but don't have any effect most of the time (though sometimes they do). No errors are shown in the console.

**Comment by randy3k** [comment]
I have no problem on my Mac OS X...could you try reinstall the package?

**Comment by certainlyakey** [comment]
Started to work somehow without a need to reinstall... Closing then. Thanks for the answer.
