### ISSUE TITLE
Pollutes directory when used with GitSavvy - show stash

### ISSUE THREAD

**Issue by mreq** [randy3k/ChangeList#13]
**Issue:**

Creates an empty `User/ChangeList.json` in project root.

**How to reproduce:**

1. create a git stash
2. use GitSavvy's `[t][s] show stash`

*Since you're working on [GitSavvy](https://github.com/divmain/GitSavvy) as well, am writing it here. Unsure whether that's caused by ChangeList or GitSavvy. Might as well be a problem in sublime.*

**Comment by randy3k** [comment]
The file `ChangeList.json` should not be in the current project directory. It should live in `sublime.packages_path()`, in my case, it is
```
'/Users/Randy/Documents/Sublime Text 3/Packages/User/ChangeList.json'
```
In fact, you don't have to create it. It will be automatically created if needed.

**Comment by mreq** [comment]
Thanks for the fast response.

That's actually the issue - the file is created the moment I open a preview of the git stash. Are you able to reproduce the issue? Might not be a problem with ChangeList, could be GitSavvy or sublime itself.

**Comment by randy3k** [comment]
I don't experience it but I guess I know what is possibly causing the issue. It seems that `sublime.packages_path()` is unable to return the package directory somehow.

**Comment by randy3k** [comment]
Hope it is fixed at 1.0.8

**Comment by mreq** [comment]
Thanks! I'll let you know once package control catches up.

**Comment by mreq** [comment]
Works great, thanks!
